<?php

// namespace App\Consts;

// class CountryConsts
// {
//   // キラメイジャーのメンバー
//   public const IS = 1;
//   public const IE = 2;
//   public const AZ = 3;
//   public const AF = 4;
//   public const US = 5;
//   public const AE = 6;
//   public const DZ = 7;
//   public const AR = 8;
//   public const AW = 9;
//   public const AL = 10;
//   public const AM = 11;
//   public const AI = 12;
//   public const AO = 13;
//   public const AG = 14;
//   public const AD = 15;
//   public const YE = 16;
//   public const GB = 17;
//   public const IL = 18; 
//   public const IT = 19;
//   public const IQ = 20;
//   public const IR = 21;
//   public const IN = 22;
//   public const ID = 23;
//   public const WF = 24;
//   public const UG = 25;
//   public const UA = 26;
//   public const UZ = 27;
//   public const UY = 28;
//   public const EC = 29;
//   public const EG = 30; 
//   public const EE = 31; 
//   public const SZ = 32; 
//   public const ET = 33; 
//   public const ER = 34; 
//   public const SV = 35; 
//   public const AU = 36; 
//   public const AT = 37; 
//   public const OM = 38; 
//   public const NL = 39; 
//   public const GH = 40; 
//   public const CV = 41; 
//   public const GG = 42; 
//   public const GY = 43; 
//   public const KZ = 44; 
//   public const QA = 45; 
//   public const CA = 46; 
//   public const GA = 47; 
//   public const CM = 48; 
//   public const GM = 49; 
//   public const KH = 50; 
//   public const GN = 51; 
//   public const GW = 52; 
//   public const CY = 53; 
//   public const CU = 54; 
//   public const CW = 55; 
//   public const GR = 56; 
//   public const KI = 57; 
//   public const KG = 58; 
//   public const GT = 59; 
//   public const GP = 60; 
//   public const GU = 61; 
//   public const KW = 62; 
//   public const GL = 63; 
//   public const GD = 64; 
//   public const HR = 65; 
//   public const KE = 66; 
//   public const CI = 67; 
//   public const CR = 68; 
//   public const KM = 69; 
//   public const CO = 70; 
//   public const CG = 71; 
//   public const CD = 72; 
//   public const SA = 73; 
//   public const WS = 74; 
//   public const BL = 75; 
//   public const MF = 76; 
//   public const ST = 77; 
//   public const ZM = 78; 
//   public const SM = 79; 
//   public const SL = 80; 
//   public const DJ = 81; 
//   public const GI = 82; 
//   public const JE = 83; 
//   public const JM = 84; 
//   public const GE = 85; 
//   public const SY = 86; 
//   public const SG = 87; 
//   public const SX = 88; 
//   public const ZW = 89; 
//   public const CH = 90; 
//   public const SE = 91; 
//   public const SD = 92; 
//   public const ES = 93; 
//   public const SR = 94; 
//   public const LK = 95; 
//   public const SK = 96; 
//   public const SI = 97; 
//   public const SC = 98; 
//   public const SN = 99; 
//   public const RS = 100; 
//   public const KN = 101; 
//   public const SH = 102; 
//   public const LC = 103; 
//   public const SO = 104; 
//   public const TH = 105; 
//   public const TJ = 106; 
//   public const TZ = 107; 
//   public const CZ = 108; 
//   public const TD = 109; 
//   public const TN = 110; 
//   public const CL = 111; 
//   public const TV = 112; 
//   public const DK = 113; 
//   public const DE = 114; 
//   public const TG = 115; 
//   public const TK = 116; 
//   public const DO = 117; 
//   public const TT = 118; 
//   public const TM = 119; 
//   public const TR = 120; 
//   public const TO = 121; 
//   public const NG = 122; 
//   public const NR = 123; 
//   public const NA = 124; 
//   public const NU = 125; 
//   public const NI = 126; 
//   public const NE = 127; 
//   public const NC = 128; 
//   public const NZ = 129; 
//   public const NP = 130; 
//   public const NO = 131; 
//   public const BH = 132; 
//   public const HT = 133; 
//   public const PK = 134; 
//   public const VA = 135; 
//   public const PA = 136; 
//   public const VU = 137; 
//   public const BS = 138; 
//   public const PG = 139; 
//   public const BM = 140; 
//   public const PW = 141; 
//   public const PY = 142; 
//   public const BB = 143; 
//   public const PS = 144; 
//   public const HU = 145; 
//   public const BD = 146; 
//   public const FJ = 147; 
//   public const PH = 148; 
//   public const FI = 149; 
//   public const BT = 150; 
//   public const PR = 151; 
//   public const BR = 152; 
//   public const FR = 153; 
//   public const BG = 154; 
//   public const BF = 155; 
//   public const BN = 156; 
//   public const BI = 157; 
//   public const VN = 158; 
//   public const BJ = 159; 
//   public const VE = 160; 
//   public const BY = 161; 
//   public const BZ = 162; 
//   public const PE = 163; 
//   public const BE = 164; 
//   public const PL = 165; 
//   public const BA = 166; 
//   public const BW = 167; 
//   public const BO = 168; 
//   public const PT = 169; 
//   public const HN = 170; 
//   public const MG = 171; 
//   public const YT = 172; 
//   public const MW = 173; 
//   public const ML = 174; 
//   public const MT = 175; 
//   public const MQ = 176; 
//   public const MY = 177; 
//   public const FM = 178; 
//   public const MM = 179; 
//   public const MX = 180; 
//   public const MU = 181; 
//   public const MR = 182; 
//   public const MZ = 183; 
//   public const MC = 184; 
//   public const MV = 185; 
//   public const MD = 186; 
//   public const MA = 187; 
//   public const MN = 188; 
//   public const ME = 189; 
//   public const MS = 190; 
//   public const JO = 191; 
//   public const LA = 192; 
//   public const LV = 193; 
//   public const LT = 194; 
//   public const LY = 195; 
//   public const LI = 196; 
//   public const LR = 197; 
//   public const RO = 198; 
//   public const LU = 199; 
//   public const RW = 200; 
//   public const LS = 201; 
//   public const LB = 202; 
//   public const RE = 203; 
//   public const RU = 204; 
//   public const KR = 205; 
//   public const EH = 206; 
//   public const GQ = 207; 
//   public const TW = 208; 
//   public const CF = 209; 
//   public const CN = 210; 
//   public const TL = 211; 
//   public const ZA = 212; 
//   public const SS = 213; 
//   public const JP = 214; 

//   public const COUNTRY_LIST = [
//     'アイスランド' => self::IS,
//     'アイルランド' => self::IE,
//     'アゼルバイジャン' => self::AZ,
//     'アフガニスタン' => self::AF,
//     'アメリカ合衆国' => self::US,
//     'アラブ首長国連邦' => self::AE,
//     'アルジェリア' => self::DZ,
//     'アルゼンチン' => self::AR,
//     'アルバ' => self::AW,
//     'アルバニア' => self::AL,
//     'アルメニア' => self::AM,
//     'アンギラ' => self::AI,
//     'アンゴラ' => self::AO,
//     'アンティグア・バーブーダ' => self::AG,
//     'アンドラ' => self::AD,
//     'イエメン' => self::YE,
//     'イギリス' => self::GB,
//     'イスラエル' => self::IL,
//     'イタリア' => self::IT,
//     'イラク' => self::IQ,
//     'イラン' => self::IR,
//     'インド' => self::IN,
//     'インドネシア' => self::ID,
//     'ウォリス・フツナ' => self::WF,
//     'ウガンダ' => self::UG,
//     'ウクライナ' => self::UA,
//     'ウズベキスタン' => self::UZ,
//     'ウルグアイ' => self::UY,
//     'エクアドル' => self::EC,
//     'エジプト' => self::EG,
//     'エストニア' => self::EE,
//     'エスワティニ' => self::SZ,
//     'エチオピア' => self::ET,
//     'エリトリア' => self::ER,
//     'エルサルバドル' => self::SV,
//     'オーストラリア' => self::AU,
//     'オーストリア' => self::AT,
//     'オマーン' => self::OM,
//     'オランダ' => self::NL,
//     'ガーナ' => self::GH,
//     'カーボベルデ' => self::CV,
//     'ガーンジー' => self::GG,
//     'ガイアナ' => self::GY,
//     'カザフスタン' => self::KZ,
//     'カタール' => self::QA,
//     'カナダ' => self::CA,
//     'ガボン' => self::GA,
//     'カメルーン' => self::CM,
//     'ガンビア' => self::GM,
//     'カンボジア' => self::KH,
//     'ギニア' => self::GN,
//     'ギニアビサウ' => self::GW,
//     'キプロス' => self::CY,
//     'キューバ' => self::CU,
//     'キュラソー' => self::CW,
//     'ギリシャ' => self::GR,
//     'キリバス' => self::KI,
//     'キルギス' => self::KG,
//     'グアテマラ' => self::GT,
//     'グアドループ' => self::GP,
//     'グアム' => self::GU,
//     'クウェート' => self::KW,
//     'グリーンランド' => self::GL,
//     'グレナダ' => self::GD,
//     'クロアチア' => self::HR,
//     'ケニア' => self::KE,
//     'コートジボワール' => self::CI,
//     'コスタリカ' => self::CR,
//     'コモロ' => self::KM,
//     'コロンビア' => self::CO,
//     'コンゴ共和国(ブラザビル)' => self::CG,
//     'コンゴ民主共和国(キンシャサ)' => self::CD,
//     'サウジアラビア' => self::SA,
//     'サモア' => self::WS,
//     'サン・バルテルミー' => self::BL,
//     'サン・マルタン' => self::MF,
//     'サントメ・プリンシペ' => self::ST,
//     'ザンビア' => self::ZM,
//     'サンマリノ' => self::SM,
//     'シエラレオネ' => self::SL,
//     'ジブチ' => self::DJ,
//     'ジブラルタル' => self::GI,
//     'ジャージー' => self::JE,
//     'ジャマイカ' => self::JM,
//     'ジョージア' => self::GE,
//     'シリア' => self::SY,
//     'シンガポール' => self::SG,
//     'シント・マールテン' => self::SX,
//     'ジンバブエ' => self::ZW,
//     'スイス' => self::CH,
//     'スウェーデン' => self::SE,
//     'スーダン' => self::SD,
//     'スペイン' => self::ES,
//     'スリナム' => self::SR,
//     'スリランカ' => self::LK,
//     'スロバキア' => self::SK,
//     'スロベニア' => self::SI,
//     'セーシェル' => self::SC,
//     'セネガル' => self::SN,
//     'セルビア' => self::RS,
//     'セントクリストファー・ネーヴィス' => self::KN,
//     'セントヘレナ' => self::SH,
//     'セントルシア' => self::LC,
//     'ソマリア' => self::SO,
//     'タイ' => self::TH,
//     'タジキスタン' => self::TJ,
//     'タンザニア' => self::TZ,
//     'チェコ' => self::CZ,
//     'チャド' => self::TD,
//     'チュニジア' => self::TN,
//     'チリ' => self::CL,
//     'ツバル' => self::TV,
//     'デンマーク' => self::DK,
//     'ドイツ' => self::DE,
//     'トーゴ' => self::TG,
//     'トケラウ' => self::TK,
//     'ドミニカ共和国' => self::DO,
//     'トリニダード・トバゴ' => self::TT,
//     'トルクメニスタン' => self::TM,
//     'トルコ' => self::TR,
//     'トンガ' => self::TO,
//     'ナイジェリア' => self::NG,
//     'ナウル' => self::NR,
//     'ナミビア' => self::NA,
//     'ニウエ' => self::NU,
//     'ニカラグア' => self::NI,
//     'ニジェール' => self::NE,
//     'ニューカレドニア' => self::NC,
//     'ニュージーランド' => self::NZ,
//     'ネパール' => self::NP,
//     'ノルウェー' => self::NO,
//     'バーレーン' => self::BH,
//     'ハイチ' => self::HT,
//     'パキスタン' => self::PK,
//     'バチカン市国' => self::VA,
//     'パナマ' => self::PA,
//     'バヌアツ' => self::VU,
//     'バハマ' => self::BS,
//     'パプアニューギニア' => self::PG,
//     'バミューダ' => self::BM,
//     'パラオ' => self::PW,
//     'パラグアイ' => self::PY,
//     'バルバドス' => self::BB,
//     'パレスチナ自治区' => self::PS,
//     'ハンガリー' => self::HU,
//     'バングラデシュ' => self::BD,
//     'フィジー' => self::FJ,
//     'フィリピン' => self::PH,
//     'フィンランド' => self::FI,
//     'ブータン' => self::BT,
//     'プエルトリコ' => self::PR,
//     'ブラジル' => self::BR,
//     'フランス' => self::FR,
//     'ブルガリア' => self::BG,
//     'ブルキナファソ' => self::BF,
//     'ブルネイ' => self::BN,
//     'ブルンジ' => self::BI,
//     'ベトナム' => self::VN,
//     'ベナン' => self::BJ,
//     'ベネズエラ' => self::VE,
//     'ベラルーシ' => self::BY,
//     'ベリーズ' => self::BZ,
//     'ペルー' => self::PE,
//     'ベルギー' => self::BE,
//     'ポーランド' => self::PL,
//     'ボスニア・ヘルツェゴビナ' => self::BA,
//     'ボツワナ' => self::BW,
//     'ボリビア' => self::BO,
//     'ポルトガル' => self::PT,
//     'ホンジュラス' => self::HN,
//     'マダガスカル' => self::MG,
//     'マヨット' => self::YT,
//     'マラウイ' => self::MW,
//     'マリ' => self::ML,
//     'マルタ' => self::MT,
//     'マルティニーク' => self::MQ,
//     'マレーシア' => self::MY,
//     'ミクロネシア連邦' => self::FM,
//     'ミャンマー (ビルマ)' => self::MM,
//     'メキシコ' => self::MX,
//     'モーリシャス' => self::MU,
//     'モーリタニア' => self::MR,
//     'モザンビーク' => self::MZ,
//     'モナコ' => self::MC,
//     'モルディブ' => self::MV,
//     'モルドバ' => self::MD,
//     'モロッコ' => self::MA,
//     'モンゴル' => self::MN,
//     'モンテネグロ' => self::ME,
//     'モントセラト' => self::MS,
//     'ヨルダン' => self::JO,
//     'ラオス' => self::LA,
//     'ラトビア' => self::LV,
//     'リトアニア' => self::LT,
//     'リビア' => self::LY,
//     'リヒテンシュタイン' => self::LI,
//     'リベリア' => self::LR,
//     'ルーマニア' => self::RO,
//     'ルクセンブルク' => self::LU,
//     'ルワンダ' => self::RW,
//     'レソト' => self::LS,
//     'レバノン' => self::LB,
//     'レユニオン' => self::RE,
//     'ロシア' => self::RU,
//     '韓国' => self::KR,
//     '西サハラ' => self::EH,
//     '赤道ギニア' => self::GQ,
//     '台湾' => self::TW,
//     '中央アフリカ共和国' => self::CF,
//     '中国' => self::CN,
//     '東ティモール' => self::TL,
//     '南アフリカ' => self::ZA,
//     '南スーダン' => self::SS,
//     '日本' => self::JP,
//   ];

  
  // public const KIRAMEI_RED = 1;
  // public const KIRAMEI_YELLOW = 2;
  // public const KIRAMEI_GREEN = 3;
  // public const KIRAMEI_BLUE = 4;
  // public const KIRAMEI_PINK = 5;
  // public const KIRAMEI_SILVER = 6;
  // public const MEMBER_LIST = [
  //   'キラメイレッド' => self::KIRAMEI_RED,
  //   'キラメイイエロー' => self::KIRAMEI_YELLOW,
  //   'キラメイグリーン' => self::KIRAMEI_GREEN,
  //   'キラメイブルー' => self::KIRAMEI_BLUE,
  //   'キラメイピンク' => self::KIRAMEI_PINK,
  //   'キラメイシルバー' => self::KIRAMEI_SILVER,
  // ];
  return [
    'countries' => [
      'IS' => 'アイスランド',
      'IE' => 'アイルランド',
      'AZ' => 'アゼルバイジャン',
      'AF' => 'アフガニスタン',
      'US' => 'アメリカ合衆国',
      'AE' => 'アラブ首長国連邦',
      'DZ' => 'アルジェリア',
      'AR' => 'アルゼンチン',
      'AW' => 'アルバ',
      'AL' => 'アルバニア',
      'AM' => 'アルメニア',
      'AI' => 'アンギラ',
      'AO' => 'アンゴラ',
      'AG' => 'アンティグア・バーブーダ',
      'AD' => 'アンドラ',
      'YE' => 'イエメン',
      'GB' => 'イギリス',
      'IL' => 'イスラエル',
      'IT' => 'イタリア',
      'IQ' => 'イラク',
      'IR' => 'イラン',
      'IN' => 'インド',
      'ID' => 'インドネシア',
      'WF' => 'ウォリス・フツナ',
      'UG' => 'ウガンダ',
      'UA' => 'ウクライナ',
      'UZ' => 'ウズベキスタン',
      'UY' => 'ウルグアイ',
      'EC' => 'エクアドル',
      'EG' => 'エジプト',
      'EE' => 'エストニア',
      'SZ' => 'エスワティニ',
      'ET' => 'エチオピア',
      'ER' => 'エリトリア',
      'SV' => 'エルサルバドル',
      'AU' => 'オーストラリア',
      'AT' => 'オーストリア',
      'AX' => 'オーランド諸島',
      'OM' => 'オマーン',
      'NL' => 'オランダ',
      'BQ' => 'オランダ領カリブ',
      'GH' => 'ガーナ',
      'CV' => 'カーボベルデ',
      'GG' => 'ガーンジー',
      'GY' => 'ガイアナ',
      'KZ' => 'カザフスタン',
      'QA' => 'カタール',
      'CA' => 'カナダ',
      'GA' => 'ガボン',
      'CM' => 'カメルーン',
      'GM' => 'ガンビア',
      'KH' => 'カンボジア',
      'GN' => 'ギニア',
      'GW' => 'ギニアビサウ',
      'CY' => 'キプロス',
      'CU' => 'キューバ',
      'CW' => 'キュラソー',
      'GR' => 'ギリシャ',
      'KI' => 'キリバス',
      'KG' => 'キルギス',
      'GT' => 'グアテマラ',
      'GP' => 'グアドループ',
      'GU' => 'グアム',
      'KW' => 'クウェート',
      'CK' => 'クック諸島',
      'GL' => 'グリーンランド',
      'CX' => 'クリスマス島',
      'GD' => 'グレナダ',
      'HR' => 'クロアチア',
      'KY' => 'ケイマン諸島',
      'KE' => 'ケニア',
      'CI' => 'コートジボワール',
      'CC' => 'ココス(キーリング)諸島',
      'CR' => 'コスタリカ',
      'KM' => 'コモロ',
      'CO' => 'コロンビア',
      'CG' => 'コンゴ共和国(ブラザビル)',
      'CD' => 'コンゴ民主共和国(キンシャサ)',
      'SA' => 'サウジアラビア',
      'GS' => 'サウスジョージア・サウスサンドウィッチ諸島',
      'WS' => 'サモア',
      'BL' => 'サン・バルテルミー',
      'MF' => 'サン・マルタン',
      'ST' => 'サントメ・プリンシペ',
      'ZM' => 'ザンビア',
      'PM' => 'サンピエール島・ミクロン島',
      'SM' => 'サンマリノ',
      'SL' => 'シエラレオネ',
      'DJ' => 'ジブチ',
      'GI' => 'ジブラルタル',
      'JE' => 'ジャージー',
      'JM' => 'ジャマイカ',
      'GE' => 'ジョージア',
      'SY' => 'シリア',
      'SG' => 'シンガポール',
      'SX' => 'シント・マールテン',
      'ZW' => 'ジンバブエ',
      'CH' => 'スイス',
      'SE' => 'スウェーデン',
      'SD' => 'スーダン',
      'SJ' => 'スバールバル諸島・ヤンマイエン島',
      'ES' => 'スペイン',
      'SR' => 'スリナム',
      'LK' => 'スリランカ',
      'SK' => 'スロバキア',
      'SI' => 'スロベニア',
      'SC' => 'セーシェル',
      'SN' => 'セネガル',
      'RS' => 'セルビア',
      'KN' => 'セントクリストファー・ネーヴィス',
      'VC' => 'セントビンセント及びグレナディーン諸島',
      'SH' => 'セントヘレナ',
      'LC' => 'セントルシア',
      'SO' => 'ソマリア',
      'SB' => 'ソロモン諸島',
      'TC' => 'タークス・カイコス諸島',
      'TH' => 'タイ',
      'TJ' => 'タジキスタン',
      'TZ' => 'タンザニア',
      'CZ' => 'チェコ',
      'TD' => 'チャド',
      'TN' => 'チュニジア',
      'CL' => 'チリ',
      'TV' => 'ツバル',
      'DK' => 'デンマーク',
      'DE' => 'ドイツ',
      'TG' => 'トーゴ',
      'TK' => 'トケラウ',
      'DO' => 'ドミニカ共和国',
      'DM' => 'ドミニカ国',
      'TT' => 'トリニダード・トバゴ',
      'TM' => 'トルクメニスタン',
      'TR' => 'トルコ',
      'TO' => 'トンガ',
      'NG' => 'ナイジェリア',
      'NR' => 'ナウル',
      'NA' => 'ナミビア',
      'NU' => 'ニウエ',
      'NI' => 'ニカラグア',
      'NE' => 'ニジェール',
      'NC' => 'ニューカレドニア',
      'NZ' => 'ニュージーランド',
      'NP' => 'ネパール',
      'NF' => 'ノーフォーク島',
      'NO' => 'ノルウェー',
      'HM' => 'ハード島・マクドナルド諸島',
      'BH' => 'バーレーン',
      'HT' => 'ハイチ',
      'PK' => 'パキスタン',
      'VA' => 'バチカン市国',
      'PA' => 'パナマ',
      'VU' => 'バヌアツ',
      'BS' => 'バハマ',
      'PG' => 'パプアニューギニア',
      'BM' => 'バミューダ',
      'PW' => 'パラオ',
      'PY' => 'パラグアイ',
      'BB' => 'バルバドス',
      'PS' => 'パレスチナ自治区',
      'HU' => 'ハンガリー',
      'BD' => 'バングラデシュ',
      'PN' => 'ピトケアン諸島',
      'FJ' => 'フィジー',
      'PH' => 'フィリピン',
      'FI' => 'フィンランド',
      'BT' => 'ブータン',
      'BV' => 'ブーベ島',
      'PR' => 'プエルトリコ',
      'FO' => 'フェロー諸島',
      'FK' => 'フォークランド諸島',
      'BR' => 'ブラジル',
      'FR' => 'フランス',
      'BG' => 'ブルガリア',
      'BF' => 'ブルキナファソ',
      'BN' => 'ブルネイ',
      'BI' => 'ブルンジ',
      'VN' => 'ベトナム',
      'BJ' => 'ベナン',
      'VE' => 'ベネズエラ',
      'BY' => 'ベラルーシ',
      'BZ' => 'ベリーズ',
      'PE' => 'ペルー',
      'BE' => 'ベルギー',
      'PL' => 'ポーランド',
      'BA' => 'ボスニア・ヘルツェゴビナ',
      'BW' => 'ボツワナ',
      'BO' => 'ボリビア',
      'PT' => 'ポルトガル',
      'HN' => 'ホンジュラス',
      'MH' => 'マーシャル諸島',
      'MG' => 'マダガスカル',
      'YT' => 'マヨット',
      'MW' => 'マラウイ',
      'ML' => 'マリ',
      'MT' => 'マルタ',
      'MQ' => 'マルティニーク',
      'MY' => 'マレーシア',
      'IM' => 'マン島',
      'FM' => 'ミクロネシア連邦',
      'MM' => 'ミャンマー (ビルマ)',
      'MX' => 'メキシコ',
      'MU' => 'モーリシャス',
      'MR' => 'モーリタニア',
      'MZ' => 'モザンビーク',
      'MC' => 'モナコ',
      'MV' => 'モルディブ',
      'MD' => 'モルドバ',
      'MA' => 'モロッコ',
      'MN' => 'モンゴル',
      'ME' => 'モンテネグロ',
      'MS' => 'モントセラト',
      'JO' => 'ヨルダン',
      'LA' => 'ラオス',
      'LV' => 'ラトビア',
      'LT' => 'リトアニア',
      'LY' => 'リビア',
      'LI' => 'リヒテンシュタイン',
      'LR' => 'リベリア',
      'RO' => 'ルーマニア',
      'LU' => 'ルクセンブルク',
      'RW' => 'ルワンダ',
      'LS' => 'レソト',
      'LB' => 'レバノン',
      'RE' => 'レユニオン',
      'RU' => 'ロシア',
      'IO' => '英領インド洋地域',
      'VG' => '英領ヴァージン諸島',
      'KR' => '韓国',
      'UM' => '合衆国領有小離島',
      'EH' => '西サハラ',
      'GQ' => '赤道ギニア',
      'TW' => '台湾',
      'CF' => '中央アフリカ共和国',
      'MO' => '中華人民共和国マカオ特別行政区',
      'HK' => '中華人民共和国香港特別行政区',
      'CN' => '中国',
      'TL' => '東ティモール',
      'ZA' => '南アフリカ',
      'SS' => '南スーダン',
      'AQ' => '南極',
      'JP' => '日本',
      'GF' => '仏領ギアナ',
      'PF' => '仏領ポリネシア',
      'TF' => '仏領極南諸島',
      'VI' => '米領ヴァージン諸島',
      'AS' => '米領サモア',
      'MK' => '北マケドニア',
      'MP' => '北マリアナ諸島',
      'KP' => '北朝鮮',
    ],
  ];